### ISSUE TITLE
[SUGGEST]

### ISSUE THREAD

**Issue by TypicalShavonne** [VoChiDanh/Jobs#1]
**Mô tả góp ý**
Open source toàn bộ plugins xd

**Comment by VoChiDanh** [comment]
Có mỗi cái này thôi, 2 plugins kia sắp tới cũng sẽ thêm vào đây

**Comment by VoChiDanh** [comment]
Nhưng theo LICENSE thì kh được copy hay dùng ké đâu :v tại code ngu nên dùng chung có khi lỗi tùm lum :v:
